version: 0.1
phases:
  #base-directory: src
  install:
    commands:
      - pip3 install boto3

  post_build:
    commands:
      - pwd
      - ls
      - ls deploy
      - deploy/deploy_lambda_functions.sh

